- name : Install codecs
  dnf:
    name:
      - transcode
      - lame
      - xine-lib 
      - gstreamer-plugins-ugly
      - gstreamer-ffmpeg
      - libdvdread
      - libdvdnav 
      - lsdvd
      - ffmpeg
      - xvidcore
      - gstreamer1-plugins-base
      - gstreamer1-plugins-good
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-bad-free-extras
      - vcdimager
      - normalize xine
      - gstreamer1-plugins-base
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-qt
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-good-gtk
      - gstreamer1-plugins-ugly-free
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-free-fluidsynth
      - gstreamer1-plugins-bad-free-wildmidi
      - gstreamer1-plugins-bad-free-zbar
      - gstreamer1-plugin-openh264
      - gstreamer1-libav
    state: latest
  retries: 3
  delay: 5
  register: result
  until: result is succeeded