- name : Install multimedia player
  dnf:
    name:
      - smplayer
      - vlc
      - amarok
      - clementine
      - elisa-player
    state: latest
  retries: 3
  delay: 5
  register: result
  until: result is succeeded