- name: Download sha256sum file of Atomic Wallet
  get_url:
    url: https://get.atomicwallet.io/download/sha256sum.txt
    dest: /tmp/sha256sum.txt

- name: Get sha256sum of rpm package for Atomic Wallet
  shell: cat /tmp/sha256sum.txt | awk '/atomicwallet.rpm/ {print $1}'
  register: sha256sum_result

- name: Download Atomic Wallet rpm file
  get_url:
    url: https://atomicwallet.io/download/atomicwallet.rpm
    dest: /tmp/atomicwallet.rpm
    checksum: sha256:{{ sha256sum_result.stdout }}
  retries: 5
  delay: 5
  register: download_atomic_wallet_rpm_file
  until: download_atomic_wallet_rpm_file is succeeded

- name : Install Atomic Wallet
  dnf:
    name:
      - /tmp/atomicwallet.rpm
    disable_gpg_check: yes
    state: present
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
