- name : Install utilitie tools
  dnf:
    name:
      - gparted
      - terminator
      - zip
      - unzip
      - unrar
      - glances
      - screen
      - rsync
      - bash-completion
      - dnf-plugins-core
    state: latest
  retries: 3
  delay: 5
  register: result
  until: result is succeeded