- name: Apply kernel tuning parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - { name: 'net.ipv4.ip_local_port_range', value: '1024 65535' }
    - { name: 'net.core.somaxconn', value: '65000' }
    - { name: 'net.ipv4.ip_unprivileged_port_start', value: '80' }
    - { name: 'net.netfilter.nf_conntrack_max', value: '1048576' }
    - { name: 'net.netfilter.nf_conntrack_tcp_timeout_established', value: '7200' }
  loop_control:
    label: "{{ item.name }}"
  when: not pre_check_dockerenv.stat.exists
