name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        override-deps: |
          ansible~=2.10
          ansible-lint~=5.0
        targets: ""

  job2:
    name: markdown-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Markdown Linting Action
      uses: avto-dev/markdown-lint@v1.5.0

  job3:
    name: build
    if: ${{ always() }}
    needs: [job1, job2]
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install ansible
      run: dnf install -y ansible

    - name: What ansible version do we have
      run: ansible --version

    - name: Deploy ansible playbook
      run: ansible-playbook main-playbook.yml
